# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dm/scratch/hooke

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dm/scratch/hooke

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dm/scratch/hooke/CMakeFiles /home/dm/scratch/hooke/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dm/scratch/hooke/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hooke

# Build rule for target.
hooke: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hooke
.PHONY : hooke

# fast build rule for target.
hooke/fast:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/build
.PHONY : hooke/fast

jog.o: jog.cpp.o
.PHONY : jog.o

# target to build an object file
jog.cpp.o:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/jog.cpp.o
.PHONY : jog.cpp.o

jog.i: jog.cpp.i
.PHONY : jog.i

# target to preprocess a source file
jog.cpp.i:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/jog.cpp.i
.PHONY : jog.cpp.i

jog.s: jog.cpp.s
.PHONY : jog.s

# target to generate assembly for a file
jog.cpp.s:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/jog.cpp.s
.PHONY : jog.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/main.cpp.s
.PHONY : main.cpp.s

motor.o: motor.cpp.o
.PHONY : motor.o

# target to build an object file
motor.cpp.o:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/motor.cpp.o
.PHONY : motor.cpp.o

motor.i: motor.cpp.i
.PHONY : motor.i

# target to preprocess a source file
motor.cpp.i:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/motor.cpp.i
.PHONY : motor.cpp.i

motor.s: motor.cpp.s
.PHONY : motor.s

# target to generate assembly for a file
motor.cpp.s:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/motor.cpp.s
.PHONY : motor.cpp.s

serialib.o: serialib.cpp.o
.PHONY : serialib.o

# target to build an object file
serialib.cpp.o:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/serialib.cpp.o
.PHONY : serialib.cpp.o

serialib.i: serialib.cpp.i
.PHONY : serialib.i

# target to preprocess a source file
serialib.cpp.i:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/serialib.cpp.i
.PHONY : serialib.cpp.i

serialib.s: serialib.cpp.s
.PHONY : serialib.s

# target to generate assembly for a file
serialib.cpp.s:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/serialib.cpp.s
.PHONY : serialib.cpp.s

setup.o: setup.cpp.o
.PHONY : setup.o

# target to build an object file
setup.cpp.o:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/setup.cpp.o
.PHONY : setup.cpp.o

setup.i: setup.cpp.i
.PHONY : setup.i

# target to preprocess a source file
setup.cpp.i:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/setup.cpp.i
.PHONY : setup.cpp.i

setup.s: setup.cpp.s
.PHONY : setup.s

# target to generate assembly for a file
setup.cpp.s:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/setup.cpp.s
.PHONY : setup.cpp.s

vars.o: vars.cpp.o
.PHONY : vars.o

# target to build an object file
vars.cpp.o:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/vars.cpp.o
.PHONY : vars.cpp.o

vars.i: vars.cpp.i
.PHONY : vars.i

# target to preprocess a source file
vars.cpp.i:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/vars.cpp.i
.PHONY : vars.cpp.i

vars.s: vars.cpp.s
.PHONY : vars.s

# target to generate assembly for a file
vars.cpp.s:
	$(MAKE) -f CMakeFiles/hooke.dir/build.make CMakeFiles/hooke.dir/vars.cpp.s
.PHONY : vars.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hooke"
	@echo "... rebuild_cache"
	@echo "... jog.o"
	@echo "... jog.i"
	@echo "... jog.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... motor.o"
	@echo "... motor.i"
	@echo "... motor.s"
	@echo "... serialib.o"
	@echo "... serialib.i"
	@echo "... serialib.s"
	@echo "... setup.o"
	@echo "... setup.i"
	@echo "... setup.s"
	@echo "... vars.o"
	@echo "... vars.i"
	@echo "... vars.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

